In [1]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

# Define dataset

X,y = make_classification(n_samples=1000, n_features=10, n_informative=5,  n_redundant=5, n_classes=3, random_state=42)

In [2]:
# Define model
y

array([0, 0, 1, 0, 0, 1, 2, 2, 0, 2, 1, 2, 1, 2, 1, 1, 0, 2, 2, 2, 1, 0,
       0, 0, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2,
       2, 2, 1, 2, 0, 2, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1,
       2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 1,
       2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 2, 0,
       2, 0, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1,
       0, 1, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2,
       0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1,
       0, 0, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 0,
       0, 2, 2, 2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 2, 2, 0, 2, 1, 0, 2, 1, 2,
       1, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 1, 0, 2, 1, 0, 2, 0, 2,
       0, 2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 2, 0, 0, 1,

In [4]:
#define the multinomial logistic regression model
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [5]:
#Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=42)

In [6]:
#train the model
model.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [8]:
y_pred = model.predict(X_test)

In [10]:
model.predict_proba(X_test)

array([[1.03512535e-01, 6.81528642e-01, 2.14958823e-01],
       [4.93432315e-01, 3.27356274e-01, 1.79211411e-01],
       [2.77833953e-01, 4.03128164e-01, 3.19037882e-01],
       [4.79425364e-03, 6.59408844e-01, 3.35796902e-01],
       [6.18032006e-01, 5.30536207e-02, 3.28914374e-01],
       [7.19077722e-01, 2.55236820e-04, 2.80667041e-01],
       [6.50620631e-02, 5.34615423e-01, 4.00322514e-01],
       [4.22413483e-01, 1.00471694e-01, 4.77114822e-01],
       [1.69173078e-01, 3.79783818e-01, 4.51043105e-01],
       [3.63467910e-01, 1.76769956e-01, 4.59762134e-01],
       [4.79791786e-01, 1.47559719e-01, 3.72648494e-01],
       [8.19550236e-01, 8.74703366e-03, 1.71702730e-01],
       [5.69965815e-01, 8.86721026e-03, 4.21166974e-01],
       [7.97069833e-01, 1.06337115e-02, 1.92296456e-01],
       [6.90424822e-01, 5.23050194e-02, 2.57270159e-01],
       [6.94391572e-01, 1.17191589e-02, 2.93889270e-01],
       [4.00546672e-01, 1.00712340e-01, 4.98740988e-01],
       [5.78404185e-02, 4.93580

In [11]:
y_pred

array([1, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 2, 2,
       2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 0, 1, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1, 2, 2, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 1,
       2, 0, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 0,
       2, 1, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 0, 2,
       1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 2, 1, 2,
       1, 1, 2, 0, 1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1])

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[54  7  7]
 [ 6 45 14]
 [14 17 36]]
              precision    recall  f1-score   support

           0       0.73      0.79      0.76        68
           1       0.65      0.69      0.67        65
           2       0.63      0.54      0.58        67

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.67       200
weighted avg       0.67      0.68      0.67       200

0.675


In [13]:
from sklearn.datasets import load_iris

In [14]:
dataset = load_iris()

In [15]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2