## Logistic Regression

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset = load_iris()

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
##To see the description of the dataset

print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [10]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

##Independent and depented features


In [17]:
df['target'] = dataset.target

In [18]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [20]:
dataset.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
## Binary classification, only taking 0 and 1

In [29]:
df_copy = df[df['target']!=2]

In [30]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

## Independent and dependent features

In [43]:
X = df_copy.iloc[:,:-1] # Independent features, all the columns except the last one
y= df_copy.iloc[:,-1] # Dependent features, only the last column

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [46]:
classifier = LogisticRegression() # Creating an object of the class

In [47]:
classifier.fit(X_train,y_train) # Training the model, fitting the model

LogisticRegression()

## Prediction


In [48]:
y_pred = classifier.predict(X_test) # Predicting the values

In [54]:
classifier.predict_proba(X_test) # Probability of the values

array([[0.00144397, 0.99855603],
       [0.01745215, 0.98254785],
       [0.00359633, 0.99640367],
       [0.96426787, 0.03573213],
       [0.93474767, 0.06525233],
       [0.96669519, 0.03330481],
       [0.99197521, 0.00802479],
       [0.03413528, 0.96586472],
       [0.97021318, 0.02978682],
       [0.97500261, 0.02499739],
       [0.94874463, 0.05125537],
       [0.95431635, 0.04568365],
       [0.00502564, 0.99497436],
       [0.98309085, 0.01690915],
       [0.01045247, 0.98954753],
       [0.97787998, 0.02212002],
       [0.00251112, 0.99748888],
       [0.00154214, 0.99845786],
       [0.96994373, 0.03005627],
       [0.95517443, 0.04482557],
       [0.00835383, 0.99164617],
       [0.02377754, 0.97622246],
       [0.95342874, 0.04657126],
       [0.98084186, 0.01915814],
       [0.0288064 , 0.9711936 ],
       [0.97695936, 0.02304064],
       [0.97877889, 0.02122111],
       [0.01705948, 0.98294052],
       [0.96439212, 0.03560788],
       [0.0018038 , 0.9981962 ],
       [0.

In [49]:
y_pred # Predicted values

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1])

### Confusion Matrix, Accuracy Score, Classification Report

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [53]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33


## Hyperparameter tuning

In [55]:
## GridSearchCV
from sklearn.model_selection import GridSearchCV , cross_val_score
import warnings
warnings.filterwarnings('ignore') , cross_val_score

In [58]:
parameters = {'penalty':('l1','l2','elasticnet','none'),
             'C':[1,10,20]
        }

In [60]:
gridscv = GridSearchCV(classifier,param_grid=parameters,cv=5)

In [62]:
## Splitting the data into training and validation data
gridscv.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', 'none')})

In [63]:
gridscv.best_params_ # Best parameters combination

{'C': 1, 'penalty': 'l2'}

In [64]:
classifier = LogisticRegression(C=1,penalty='l2')

In [72]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [73]:
## Prediction
y_pred = classifier.predict(X_test) # Predicting the values
print(confusion_matrix(y_pred,y_test)) # Confusion matrix
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))


[[19  0]
 [ 0 14]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33


## RandomizedSearchCV


In [74]:
from sklearn.model_selection import RandomizedSearchCV

In [75]:
random_scv= RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [76]:
random_scv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    'none')})

In [77]:
random_scv.best_params_

{'penalty': 'l2', 'C': 10}

In [84]:
classifier = LogisticRegression(C=10,penalty='l2')

In [85]:
classifier.fit(X_train,y_train)

LogisticRegression(C=10)

In [86]:
## Prediction

In [87]:
y_pred = classifier.predict(X_test) # Predicting the values

In [88]:
print(confusion_matrix(y_pred,y_test)) # Confusion matrix

[[19  0]
 [ 0 14]]


In [91]:
print(accuracy_score(y_pred,y_test))


1.0


In [92]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        14

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33
