## PCA IMPLEMENTATION WITH IRIS DATASET 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn import datasets

In [2]:
dataset = datasets.load_iris()

In [3]:
X = dataset['data'] # Features ##dataset.data  can also used
y = dataset['target'] # Target


In [4]:
X,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
#X_train.shape, X_test.shape, y_train.shape, y_test.shape

print(X_train.shape) #4 features

(100, 4)


In [35]:
## PCA transformation
pca = PCA(n_components=3) ## 3 components,coverting into 3D from 4D
pca

PCA(n_components=3)

In [36]:
X_train = pca.fit_transform(X_train)
X_train
#converted into 3D

array([[ 3.22902397e-01, -2.37270677e-01,  5.67385995e-02],
       [ 3.35552035e+00,  5.83049683e-01, -3.28026023e-01],
       [ 6.06909989e-01, -3.15971948e-01,  3.00676488e-01],
       [-2.72817511e+00,  4.27577132e-01,  1.15313718e-03],
       [ 3.45649511e+00,  5.05276379e-01, -5.58623842e-01],
       [ 1.81648425e-01, -2.53524117e-01, -2.95111131e-01],
       [-2.68432386e+00,  4.26081277e-01, -1.16106065e-01],
       [-2.81519461e+00,  3.65984714e-01,  1.04618538e-01],
       [-2.24998893e+00,  5.19074070e-01,  3.29384000e-01],
       [-5.78277826e-01, -1.17473663e+00, -3.43091299e-01],
       [ 1.33493144e+00, -1.58668543e-01, -7.85684488e-02],
       [-2.40366776e+00,  5.99469498e-02,  1.25799777e-01],
       [-2.55890034e+00, -2.63787007e-02, -2.52131368e-01],
       [-2.35087676e+00,  1.95931613e-01,  5.58985862e-02],
       [ 2.99984039e-01, -4.44823406e-01, -1.67008263e-02],
       [-2.63556736e+00,  3.39217011e-01, -5.69862980e-02],
       [ 2.80440519e-01, -1.55505144e-01

In [37]:
X_train.shape

(100, 3)

In [39]:
X_test = X_test[:,:3]
X_test = pca.transform(X_test)
X_test

array([[6.1, 2.8, 4.7],
       [5.7, 3.8, 1.7],
       [7.7, 2.6, 6.9],
       [6. , 2.9, 4.5],
       [6.8, 2.8, 4.8],
       [5.4, 3.4, 1.5],
       [5.6, 2.9, 3.6],
       [6.9, 3.1, 5.1],
       [6.2, 2.2, 4.5],
       [5.8, 2.7, 3.9],
       [6.5, 3.2, 5.1],
       [4.8, 3. , 1.4],
       [5.5, 3.5, 1.3],
       [4.9, 3.1, 1.5],
       [5.1, 3.8, 1.5],
       [6.3, 3.3, 4.7],
       [6.5, 3. , 5.8],
       [5.6, 2.5, 3.9],
       [5.7, 2.8, 4.5],
       [6.4, 2.8, 5.6],
       [4.7, 3.2, 1.6],
       [6.1, 3. , 4.9],
       [5. , 3.4, 1.6],
       [6.4, 2.8, 5.6],
       [7.9, 3.8, 6.4],
       [6.7, 3. , 5.2],
       [6.7, 2.5, 5.8],
       [6.8, 3.2, 5.9],
       [4.8, 3. , 1.4],
       [4.8, 3.1, 1.6],
       [4.6, 3.6, 1. ],
       [5.7, 4.4, 1.5],
       [6.7, 3.1, 4.4],
       [4.8, 3.4, 1.6],
       [4.4, 3.2, 1.3],
       [6.3, 2.5, 5. ],
       [6.4, 3.2, 4.5],
       [5.2, 3.5, 1.5],
       [5. , 3.6, 1.4],
       [5.2, 4.1, 1.5],
       [5.8, 2.7, 5.1],
       [6. , 3.4

In [23]:
pca.components_ #to check eigen vectors

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [24]:
pca.explained_variance_ratio_ #to check eigen values

array([0.92488106, 0.05523359, 0.01988534])

In [40]:
#Now we can use this transformed data for any classification algorithm


In [41]:
##Using tranfformed data to train a model

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [42]:
y_pred = model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.32


In [46]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

#Scale data
scaler = StandardScaler()
scaler

StandardScaler()

In [47]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
model = LogisticRegression()
model

LogisticRegression()

In [50]:
##train the model

model.fit(X_train_scaled, y_train)

#use cross validation to check the accuracy

score = cross_val_score(model, X_train_scaled, y_train, cv=5)
print(score)
print(score.mean())

[0.95 0.75 0.95 1.   0.9 ]
0.9099999999999999


In [51]:
#Use model to predict the test data
y_pred = model.predict(X_test_scaled)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [54]:
#Check the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"model acccuracy is {accuracy}")

model acccuracy is 0.32


In [55]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier
model = RandomForestClassifier(n_estimators=100)

# Train the model
model.fit(X_train_scaled, y_train)

# Use cross-validation to evaluate the model
scores = cross_val_score(model, X_train_scaled, y_train, cv=5)
print(f"Cross-validation scores: {scores}")
print(f"Average cross-validation score: {scores.mean()}")

# Use the model to predict the labels for the test data
y_pred = model.predict(X_test_scaled)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

print(f"Model accuracy: {accuracy}")

Cross-validation scores: [0.9  0.75 0.85 1.   0.95]
Average cross-validation score: 0.89
Model accuracy: 0.32
